package com.simplemethod.aiwd.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.Entity;
import java.io.Serializable;


@Getter @Setter @AllArgsConstructor @NoArgsConstructor
public class CSVDataModel {

    private float time_left;
    private float ct_score;
    private float t_score;
    private String map;
    private boolean bomb_planted;
    private float ct_health;
    private float t_health;
    private float ct_armor;
    private float t_armor;
    private float ct_money;
    private float t_money;
    private float ct_helmets;
    private float t_helmets;
    private float ct_defuse_kits;
    private float ct_players_alive;
    private float t_players_alive;
    private float ct_weapon_ak47;
    private float t_weapon_ak47;
    private float ct_weapon_aug;
    private float t_weapon_aug;
    private float ct_weapon_awp;
    private float t_weapon_awp;
    private float ct_weapon_bizon;
    private float t_weapon_bizon;
    private float ct_weapon_cz75auto;
    private float t_weapon_cz75auto;
    private float ct_weapon_elite;
    private float t_weapon_elite;
    private float ct_weapon_famas;
    private float t_weapon_famas;
    private float ct_weapon_g3sg1;
    private float t_weapon_g3sg1;
    private float ct_weapon_galilar;
    private float t_weapon_galilar;
    private float ct_weapon_glock;
    private float t_weapon_glock;
    private float ct_weapon_m249;
    private float t_weapon_m249;
    private float ct_weapon_m4a1s;
    private float t_weapon_m4a1s;
    private float ct_weapon_m4a4;
    private float t_weapon_m4a4;
    private float ct_weapon_mac10;
    private float t_weapon_mac10;
    private float ct_weapon_mag7;
    private float t_weapon_mag7;
    private float ct_weapon_mp5sd;
    private float t_weapon_mp5sd;
    private float ct_weapon_mp7;
    private float t_weapon_mp7;
    private float ct_weapon_mp9;
    private float t_weapon_mp9;
    private float ct_weapon_negev;
    private float t_weapon_negev;
    private float ct_weapon_nova;
    private float t_weapon_nova;
    private float ct_weapon_p90;
    private float t_weapon_p90;
    private float ct_weapon_r8revolver;
    private float t_weapon_r8revolver;
    private float ct_weapon_sawedoff;
    private float t_weapon_sawedoff;
    private float ct_weapon_scar20;
    private float t_weapon_scar20;
    private float ct_weapon_sg553;
    private float t_weapon_sg553;
    private float ct_weapon_ssg08;
    private float t_weapon_ssg08;
    private float ct_weapon_ump45;
    private float t_weapon_ump45;
    private float ct_weapon_xm1014;
    private float t_weapon_xm1014;
    private float ct_weapon_deagle;
    private float t_weapon_deagle;
    private float ct_weapon_fiveseven;
    private float t_weapon_fiveseven;
    private float ct_weapon_usps;
    private float t_weapon_usps;
    private float ct_weapon_p250;
    private float t_weapon_p250;
    private float ct_weapon_p2000;
    private float t_weapon_p2000;
    private float ct_weapon_tec9;
    private float t_weapon_tec9;
    private float ct_grenade_hegrenade;
    private float t_grenade_hegrenade;
    private float ct_grenade_flashbang;
    private float t_grenade_flashbang;
    private float ct_grenade_smokegrenade;
    private float t_grenade_smokegrenade;
    private float ct_grenade_incendiarygrenade;
    private float t_grenade_incendiarygrenade;
    private float ct_grenade_molotovgrenade;
    private float t_grenade_molotovgrenade;
    private float ct_grenade_decoygrenade;
    private float t_grenade_decoygrenade;
    private String round_winner;
}
